version: "3.6"

volumes:
  dev_postgres_data:

services:
  db:
    image: postgres:13.0
    container_name: dev_emer_db
    restart: always
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - dev_emer_network

networks:
  dev_emer_network:
    driver: bridge