# Generated by Django 3.1.7 on 2021-04-07 07:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(help_text='Часть URL адреса документа, по которому можно найти модель. Например "about-emercoin"', max_length=250, unique=True, verbose_name='Slug - URL')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>Этот раздел ещё не переведен на русский</p> <p>Вы поможете сообществу, если переведете его</p> <p>&nbsp;</p> <p><a class="button button-telegram" href="https://t.me/emernews" onclick="dataLayer.push({\'event\': \'telegram_community\'});" rel="nofollow" target="_blank">Telegram</a></p>', help_text='Текст (не более 25 тыс символов)', max_length=25000, verbose_name='Текст документа')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='<p>This section has not been translated yet.</p><p>You can help the community by translating this section into English</p><p><a class="button button-telegram" href="https://t.me/emerсoin_official" onclick="dataLayer.push({\'event\': \'telegram_community\'});" rel="nofollow" target="_blank">Telegram</a></p>', help_text='Text (no more 25K letters)', max_length=25000, verbose_name='Document text')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документация',
                'ordering': ['-pk'],
            },
        ),
    ]
