# Generated by Django 3.1.7 on 2021-04-03 14:41

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(help_text='Часть URL адреса документа, по которому можно найти модель. Например "about-emercoin"', max_length=250, unique=True, verbose_name='Slug - URL')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст (не более 25 тыс символов)', max_length=25000, verbose_name='Текст документа')),
                ('text_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Text (no more 25K letters)', max_length=25000, verbose_name='Document text')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документация',
                'ordering': ['-pk'],
            },
        ),
    ]
