# Generated by Django 3.1.7 on 2021-04-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerdocs', '0004_auto_20210408_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='docpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
