server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;

    root /site;

    # Долгий кэш для неизменяемых ассетов
    location /static/ {
        access_log off;
        expires 7d;
        try_files $uri =404;
    }
    location /media/ {
        access_log off;
        expires 7d;
        try_files $uri =404;
    }

    # Статические страницы: <path> -> <path>/index.html
    location / {
        try_files $uri $uri/index.html =404;
    }

    error_page 404 /404.html;
}
