# Generated by Django 3.1.7 on 2021-03-22 07:23

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='URL (не более 200 символов)', unique=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка на промо (Главный слайдер)')),
                ('bg_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('mobile_img', models.ImageField(height_field=350, help_text='Картинка для мобильного (450*350 пиксел)', upload_to='info/', width_field=450)),
                ('desktop_img', models.ImageField(blank=True, height_field=390, help_text='Картинка для десктопа (1110*390 пиксел)', upload_to='info/', width_field=1110)),
            ],
        ),
    ]
