# Generated by Django 3.1.7 on 2021-03-22 12:21

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(max_length=150, upload_to='info/', verbose_name='Изображение блока')),
            ],
            options={
                'verbose_name': 'Блок о блокчейне',
                'verbose_name_plural': 'Блоки о блокчейне',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'ordering': ['-pk'], 'verbose_name': 'Промо слайд', 'verbose_name_plural': 'Промо слайды'},
        ),
        migrations.AlterField(
            model_name='promo',
            name='bg_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет фона полдожки'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='desktop_img',
            field=models.ImageField(help_text='Картинка для десктопа (1110*390 пиксел, не больше 5 Мб)', max_length=150, upload_to='info/', validators=[info.models.desktop_image_validator], verbose_name='Картинка для десктопа'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='link',
            field=models.URLField(help_text='URL (не более 200 символов)', unique=True, validators=[django.core.validators.URLValidator], verbose_name='Ссылка c Промо на новость (Главный слайдер)'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='mobile_img',
            field=models.ImageField(help_text='Картинка для мобильного (450*350 пиксел) не больше 1Mb)', max_length=150, upload_to='info/', validators=[info.models.mobile_image_validator], verbose_name='Картинка для мобильного'),
        ),
    ]
