# Generated by Django 3.1.7 on 2021-03-22 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210322_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Название')),
                ('text', models.TextField(max_length=1500, verbose_name='Описание')),
                ('text_more', models.TextField(max_length=2000,
                                               verbose_name='Дополнительное описание')),
                ('scenarios', models.TextField(help_text='Список тезисисов, разделитель  - |', max_length=1000, verbose_name='Где применимо')),
                ('image', models.FileField(max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Изображение блока')),
            ],
            options={
                'verbose_name': 'Сервис Эмера',
                'verbose_name_plural': 'Сервисы Эмера',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='aboutemer',
            name='image',
            field=models.FileField(max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Изображение блока'),
        ),
    ]
