# Generated by Django 3.1.7 on 2021-03-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210322_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='scenarios',
            field=models.TextField(default='Ещё', help_text='Список тезисисов, разделитель  - |', max_length=1000, verbose_name='Где применимо'),
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Краткое описание'),
        ),
    ]
