# Generated by Django 3.1.7 on 2021-03-22 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210322_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.FileField(default=None, max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Иконка блока'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Изображение блока (большое)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='scenarios',
            field=models.TextField(default='Там | Тут', help_text='Список тезисисов, разделитель  - |', max_length=1000, verbose_name='Где применимо'),
        ),
    ]
