# Generated by Django 3.1.7 on 2021-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20210322_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['pk'], 'verbose_name': 'Сервис Эмера', 'verbose_name_plural': 'Сервисы Эмера'},
        ),
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(default='emerdns', help_text='Часть URL пути, например emerdns', verbose_name='Slug'),
        ),
    ]
