# Generated by Django 3.1.7 on 2021-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20210322_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='slug',
            field=models.SlugField(help_text='Часть URL пути, например emerdns', verbose_name='Slug'),
        ),
    ]
