# Generated by Django 3.1.7 on 2021-03-23 09:48

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20210322_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата публикаци')),
                ('link', models.URLField(verbose_name='Ссылка на публикацию')),
                ('brif', models.CharField(max_length=80, verbose_name='Заголовок публикации')),
            ],
            options={
                'verbose_name': 'Публикация СМИ',
                'verbose_name_plural': 'Публикации СМИ',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название СМИ')),
                ('logo', models.FileField(default=None, max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Логотип СМИ')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=1500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='text_more',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='Дополнительное описание'),
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.content')),
                ('t_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.media')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='contents',
            field=models.ManyToManyField(related_name='medium', through='info.MediaContent', to='info.Content'),
        ),
    ]
