# Generated by Django 3.1.7 on 2021-03-23 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20210323_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['pk'], 'verbose_name': 'СМИ', 'verbose_name_plural': 'СМИ'},
        ),
        migrations.AddField(
            model_name='media',
            name='logo_big',
            field=models.FileField(default=None, max_length=150, null=True, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Большой логотип СМИ'),
        ),
        migrations.AlterField(
            model_name='media',
            name='logo',
            field=models.FileField(default=None, max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Логотип СМИ малый'),
        ),
    ]
