# Generated by Django 3.1.7 on 2021-03-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20210323_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['date'], 'verbose_name': 'Публикация СМИ', 'verbose_name_plural': 'Публикации СМИ'},
        ),
    ]
