# Generated by Django 3.1.7 on 2021-03-24 11:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, help_text='Часть URL адреса новости, если не указывать явно - заполняется автоматически из Заголовка', max_length=250, verbose_name='Slug')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('image', models.ImageField(help_text='Изображение 420*280 (примерно)', max_length=250, upload_to='', verbose_name='Картинка новости')),
                ('text', ckeditor.fields.RichTextField(help_text='Текст (не более 10 тыс символов)', max_length=10000, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['year'], 'verbose_name': 'Год Дорожной карты', 'verbose_name_plural': 'Дорожная карта'},
        ),
    ]
