# Generated by Django 3.1.7 on 2021-03-24 13:21

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20210324_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Часть URL адреса новости, если не указывать явно - заполняется автоматически из Заголовка', max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Текст (не более 10 тыс символов)', max_length=10000, verbose_name='Текст новости'),
        ),
    ]
