# Generated by Django 3.1.7 on 2021-03-25 07:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.URLField(blank=True, max_length=250, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Не более 550 символов', max_length=550, verbose_name='Полное инфо'),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telegram',
            field=models.URLField(blank=True, max_length=250, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='twitter',
            field=models.URLField(blank=True, max_length=250, verbose_name='Twitter'),
        ),
    ]
