# Generated by Django 3.1.7 on 2021-03-25 07:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20210325_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Не более 550 символов', max_length=1500, verbose_name='Полное инфо'),
        ),
        migrations.AlterField(
            model_name='person',
            name='info_short',
            field=ckeditor.fields.RichTextField(help_text='Не более 250 символов', max_length=450, verbose_name='Краткое инфо'),
        ),
    ]
