# Generated by Django 3.1.7 on 2021-03-28 07:55

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20210325_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, help_text='Часть URL адреса новости, если не указывать явно - заполняется автоматически из Названия', max_length=250, unique=True, verbose_name='Slug')),
                ('logo', models.FileField(default=None, max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Логотип Компании малый')),
                ('logo_big', models.FileField(default=None, max_length=150, null=True, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Большой логотип Компании')),
                ('text', ckeditor.fields.RichTextField(max_length=1500, verbose_name='Краткое описание')),
                ('text_more', ckeditor.fields.RichTextField(max_length=2000, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='github',
        ),
        migrations.RemoveField(
            model_name='person',
            name='telegram',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Часть URL адреса новости, если не указывать явно - заполняется автоматически из Заголовка', max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
