# Generated by Django 3.1.7 on 2021-03-28 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20210328_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(default=None, help_text='Размер 100*40 пикселей', max_length=150, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Логотип Компании малый'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_big',
            field=models.FileField(default=None, help_text='Размер 200*80 пикселей', max_length=150, null=True, upload_to='info/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg'])], verbose_name='Большой логотип Компании'),
        ),
    ]
