# Generated by Django 3.1.7 on 2021-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_auto_20210328_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_partner',
            field=models.BooleanField(default=True, help_text='Заключили партнерство?', verbose_name='Партнер?'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Применяют технологии?', verbose_name='Применяют?'),
        ),
    ]
