# Generated by Django 3.1.7 on 2021-03-29 10:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20210328_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='scenarios_en',
            field=models.TextField(blank=True, default='Here | and Here', help_text='List of theses, divider  - |', max_length=1000, null=True, verbose_name='Where can use'),
        ),
        migrations.AddField(
            model_name='services',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1500, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='services',
            name='text_more_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='Long description'),
        ),
    ]
