# Generated by Django 3.1.7 on 2021-03-30 09:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_auto_20210329_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutemer',
            name='text_en',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='aboutemer',
            name='title_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='company',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1500, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='company',
            name='text_more_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2000, null=True, verbose_name='More description'),
        ),
    ]
