# Generated by Django 3.1.7 on 2021-03-30 09:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0022_auto_20210330_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Post (no more than 10K letters)', max_length=10000, null=True, verbose_name='News text'),
        ),
        migrations.AddField(
            model_name='promo',
            name='desktop_img_en',
            field=models.ImageField(blank=True, help_text='If exists ~(1110*390 pixel, no more 5 Мб please)', max_length=150, null=True, upload_to='info/', verbose_name='Desktop image'),
        ),
        migrations.AddField(
            model_name='promo',
            name='mobile_img_en',
            field=models.ImageField(blank=True, help_text='If exists ~(450*350 pixel) no more 1Mb please)', max_length=150, null=True, upload_to='info/', verbose_name='Mobile image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Текст (не более 10 тыс символов)', max_length=10000, verbose_name='Текст новости'),
        ),
    ]
