# Generated by Django 3.1.7 on 2021-03-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_auto_20210330_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image_en',
            field=models.ImageField(blank=True, help_text='Image ~ 420*280 px', max_length=250, null=True, upload_to='', verbose_name='News image'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
    ]
