# Generated by Django 3.1.7 on 2021-03-30 13:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_roadmap_text_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='info_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='No more 550 letters', max_length=1500, null=True, verbose_name='Full info'),
        ),
        migrations.AddField(
            model_name='person',
            name='info_short_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='No more 250 letters', max_length=450, null=True, verbose_name='Short_info'),
        ),
        migrations.AddField(
            model_name='person',
            name='name_en',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='person',
            name='whois_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='The role'),
        ),
    ]
