# Generated by Django 3.1.7 on 2021-03-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_auto_20210330_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение 420*280 (примерно)', max_length=250, upload_to='', verbose_name='Картинка новости'),
        ),
    ]
