# Generated by Django 3.1.7 on 2021-04-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_privacy_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
    ]
