# Generated by Django 3.1.7 on 2021-04-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0035_auto_20210413_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-pk'], 'verbose_name': 'СМИ', 'verbose_name_plural': 'СМИ'},
        ),
    ]
