name: Emercoin site

on:
  push:
    branches:
      - master

jobs:

  deploy:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:

      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@v0.1.3
        env:
          MY_ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.TEST_HOST }}
          username: ${{ secrets.TEST_HOST_ADMIN }}
          key: ${{ secrets.SSH_KEY }}
          envs: MY_ENV
          script: |
            cd emercoin
            git pull
            sudo touch .env && echo "$MY_ENV" | sudo tee .env
            sudo docker image prune -f
            sudo docker-compose down
            sudo docker volume rm emercoin_media_volume
            sudo docker volume rm emercoin_postgres_data
            sudo docker-compose up -d --build
            sudo docker cp .env emer_web:/code/

  send_message:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} выполнен успешно!
